using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("Ninject.Web: Web extension for Ninject")]
[assembly: AssemblyCompanyAttribute("Enkari, Ltd.")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2007-2009 Enkari, Ltd. and contributors")]
[assembly: AssemblyVersionAttribute("2.1.0.4")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]

